services:
  strapi:
    container_name: strapi-app-dev
    ports:
      - "1337:1337"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    restart: unless-stopped
    environment:
      # Server
      NODE_ENV: development
      HOST: 0.0.0.0
      STRAPI_PORT: 1337
      STRAPI_URL: https://strapi.budokanryu.com.br
      
      # Database
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapi-mysql-dev
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi-development
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: false
      
      # Secrets
      APP_KEYS: "4jkZEXetMUmy79/lLwsigw==,3YgxGuRZXlCg4DOKaqD03w==,4YqEUnAOAOeuThLNhai9vQ==,oLqhiS92Maztw75vcm96hg=="
      API_TOKEN_SALT: wMCiZnn0asYx9qzs4ZE8mA==
      ADMIN_JWT_SECRET: T1InRz2Lh4VW0gtxbzR0EQ==
      TRANSFER_TOKEN_SALT: zlgEAVrGtrbLNJg0aW368Q==
      ENCRYPTION_KEY: eVFU/fHQV//xxHILoUgQSA==
      JWT_SECRET: 8+sFI4UZXwgNKwcrvurwZQ==
      
      ENVIRONMENT_MODE: "🚀 DEVELOPMENT MODE ACTIVE 🚀"
    volumes:
      - strapi-uploads:/opt/app/public/uploads
      - strapi-data:/opt/app/data
    networks:
      - strapi-network
    depends_on:
      strapi-mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/_health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: sh -c "echo '🚀 STARTING STRAPI IN DEVELOPMENT MODE 🚀' && npm run develop"

  strapi-mysql:
    container_name: strapi-mysql-dev
    image: mysql:8.0.35
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: strapi-budokanryu
      MYSQL_DATABASE: strapi-development
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - strapi-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pstrapi-budokanryu",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    container_name: strapi-redis-dev
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass strapi-budokanryu
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - strapi-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mysql-data:
    driver: local
  strapi-uploads:
    driver: local
  strapi-data:
    driver: local
  redis-data:
    driver: local

networks:
  strapi-network:
    driver: bridge
